model: "gemini-3-flash-preview"
base_url: "https://ssvip.dmxapi.com/v1"

tasks:
  - domain: Recsys
    task: MMRec
    metric: "recall@20"
    seeds: ["PGL_2025"]

  # - domain: timeseries
  #   task: long_term_forecast
  #   metric: "mse"
  #   seeds: ["iTransformer_2023"]

max_rounds: 10
patience: 3
