task_name: anomaly_detection
is_training: 1
model_id: MSL
model: FEDformer
features: M
seq_len: 100
pred_len: 0
d_model: 128
d_ff: 512
n_heads: 8
e_layers: 2
dropout: 0.1
embed: timeF
freq: h
activation: gelu
anomaly_ratio: 1
batch_size: 128
learning_rate: 0.0001
train_epochs: 10
patience: 3
lradj: type1